(function(){function d(a){return!a?null:document.getElementById(a)}function g(){a(".switchstyle").mouseenter(function(){if(!d("ttmp")){a("body").append('<div id="ttmp"><ul><li>\u5c0f</li><li>\u4e2d</li><li>\u5927</li></ul></div>');var c=a("#ttmp");c.css({left:this.offsetLeft,top:this.offsetTop,width:this.offsetWidth,height:"65px",display:"none"});c.stop().fadeIn();c.mouseleave(function(){a("#ttmp").stop().fadeOut("normal",function(){a("#ttmp").remove()})});a("ul li",c).click(function(){a("#ttmp").stop().fadeOut("normal",
function(){a("#ttmp").remove()});MGJS_CMT.widthswitch(this);a("#return_top a").trigger("click")})}})}function i(a){if(!d("extstyle"))css=document.createElement("link"),css.id="extstyle",css.type="text/css",css.rel="stylesheet",document.getElementsByTagName("head")[0].appendChild(css);d("extstyle").href="/usr/themes/mono/"+a+".css";j("extstyle",a,31104E3)}function j(a,e,f,d,h,g){var b=new Date;if(e==""||f<0)e="",f=-2592E3;b.setTime(b.getTime()+f*1E3);h=!h?l:h;d=!d?m:d;document.cookie=escape(n+a)+"="+
escape(e)+(b?"; expires="+b.toGMTString():"")+(d?"; path="+d:"/")+(h?"; domain="+h:"")+(g?"; secure":"")}function k(){a("a").bind("focus",function(){this.blur&&this.blur()});a(".menu > li:first-child").addClass("first_menu");a(".menu > li:first-child.current_page_item, .menu > li:first-child.current-menu-item").addClass("first_menu_active").removeClass("first_menu");a(".menu > li:last-child").addClass("last_menu");a(".menu > li:last-child.current_page_item, .menu > li:last-child.current-menu-item").addClass("last_menu_active").removeClass("last_menu");
a(".menu li ul li:has(ul)").addClass("parent_menu");a("ol.comment-list li.admin-comment ul.children").parent().removeClass("admin-comment");a("#comment_area ol > li:even").addClass("even_comment");a("#comment_area ol > li:odd").addClass("odd_comment");a(".even_comment > .children > li").addClass("even_comment_children");a(".odd_comment > .children > li").addClass("odd_comment_children");a(".even_comment_children > .children > li").addClass("odd_comment_children");a(".odd_comment_children > .children > li").addClass("even_comment_children");
a(".even_comment_children > .children > li").addClass("odd_comment_children");a(".odd_comment_children > .children > li").addClass("even_comment_children");a("#guest_info input,#comment_textarea textarea").focus(function(){a(this).css({borderColor:"#33a8e5"})}).blur(function(){a(this).css({borderColor:"#ccc"})});a("#tag_list ul").hide();a(".search_tag").toggle(function(){a(this).addClass("active_search_tag")},function(){a(this).removeClass("active_search_tag")});a(".search_tag").click(function(){a(this).next("#tag_list ul").slideToggle("300")});
a("#trackback_switch").click(function(){a("#comment_switch").removeClass("comment_switch_active");a(this).addClass("comment_switch_active");a("#comment_area").slideUp();a("#trackback_area").slideDown();return false});a("#comment_switch").click(function(){a("#trackback_switch").removeClass("comment_switch_active");a(this).addClass("comment_switch_active");a("#trackback_area").slideUp();a("#comment_area").slideDown();return false});a("#guest_info input,#comment_textarea textarea").focus(function(){a(this).css({borderColor:"#33a8e5"})}).blur(function(){a(this).css({borderColor:"#ccc"})});
a("blockquote").append('<div class="quote_bottom"></div>');a(".side_box:first").addClass("first_side_box")}function o(){a("a[href*=#wrapper],a[href*=#respond]").click(function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")&&location.hostname==this.hostname){var c=a(this.hash),c=c.length&&c||a("[name="+this.hash.slice(1)+"]");if(c.length)return c=c.offset().top,document.addEventListener?document.addEventListener(a.browser.mozilla?"DOMMouseScroll":"mousewheel",b,false):document.attachEvent&&
document.attachEvent("onmousewheel",b),a("html,body").animate({scrollTop:c},1E3,"quart"),false}})}function b(){a("html,body").stop(true);document.removeEventListener?document.removeEventListener(a.browser.mozilla?"DOMMouseScroll":"mousewheel",b,false):document.removeEvent&&document.removeEvent("onmousewheel",b)}function p(c,e){comment=this.dom(c);parent=comment.parentNode;response=a(".respond")[0];var f=this.dom("comment-parent"),d="form"==response.tagName?response:response.getElementsByTagName("form")[0],
b=response.getElementsByTagName("textarea")[0];null==f&&(f=this.create("input",{type:"hidden",name:"parent",id:"comment-parent"}),d.appendChild(f));f.setAttribute("value",e);if(null!=this.dom("comment-form-place-holder")){if(a(comment).children("div.respond").length!=0)return MGJS_CMT.custom_scroll(response,function(){b.focus()}),false}else f=this.create("div",{id:"comment-form-place-holder"}),response.parentNode.insertBefore(f,response);a("#cancel-comment-reply-link").show();a(response).hide();comment.appendChild(response);
null!=b&&"text"==b.name&&(a(response).slideDown(300),MGJS_CMT.custom_scroll(response,function(){b.focus()}));return false}function q(){var c=a(".respond")[0],e=this.dom("comment-form-place-holder"),b=this.dom("comment-parent");null!=b&&b.parentNode.removeChild(b);if(null==e)return false;a(c).slideUp(1E3,function(){a("#cancel-comment-reply-link").hide();e.parentNode.insertBefore(this,e);a(e).remove();a(c).slideDown()});return false}function r(){a("ul.comment-act").fadeOut();if(a(".comment_form_wrapper").length)d("comment").onkeydown=
function(a){var b=null,b=window.event?window.event:a;b!=null&&b.ctrlKey&&b.keyCode==13&&d("submit_comment").click()},a("li.comments div").hover(function(){a(this).children("div.comment-meta ul.comment-act").stop(false,true).fadeIn(100)},function(){a(this).children("div.comment-meta ul.comment-act").stop(false,true).fadeOut(1E3)})}var l="",m="/",n="__typecho_",a=jQuery;window.MGJS={};window.MGJS_CMT={};window.MGJS_CMT.custom_scroll=function(c,d){document.addEventListener?document.addEventListener(a.browser.mozilla?
"DOMMouseScroll":"mousewheel",b,false):document.attachEvent&&document.attachEvent("onmousewheel",b);return a("html").animate({scrollTop:c.offsetTop-window.outerHeight/4},1E3,"quart",d)};window.MGJS_CMT.widthswitch=function(b){b.innerHTML=="\u5c0f"?i("width_930px"):b.innerHTML=="\u5927"?i("width_1100px"):(d("extstyle")&&a("#extstyle").remove(),j("extstyle","",-1))};window.MGJS_CMT.init=function(){a(function(){a("#loading").fadeOut(1E3)});k();a("a[rel*='external']").click(function(){window.open(this.href);
return false});a("ol.page-navigator li.current a").removeAttr("href");r();o();g()};if(null!=window.TypechoComment)window.TypechoComment.reply=p,window.TypechoComment.cancelReply=q})();jQuery.easing.quart=function(d,g,i,j,k){return-j*((g=g/k-1)*g*g*g-1)+i};$(function(){MGJS_CMT.init(this)});
